format_version: 4
pipelines:
  "prm-migration-poc":
    group: prm
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - build:
          clean_workspace: true
          jobs:
            build:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test
