format_version: 4
pipelines:
  "prm-migration-poc":
    group: prm
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    secure_variables:
      DOCKERHUB_PASSWORD: "AES:l4TzO03XGM1O6tbRiKzxOA==:2xZ/bnmj+KFy4VUQbmwJgD/6/VxTpnXv6Q9s1Sgu6UmzAPToxJsgqdPIdYOt1P1r"
    stages:
      - build:
          clean_workspace: true
          jobs:
            build:
              resources:
                - docker
              artifacts:
                - build:
                    source: out
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build
            test:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test
      - docker:
          clean_workspace: true
          jobs:
            build:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: build
                    job: build
                    source: out
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks build_docker
      - test_docker:
          clean_workspace: true
          jobs:
            test:
              resources:
                - docker
              tasks:
                - fetch:
                    stage: build
                    job: build
                    source: out
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_docker
      - deploy:
          clean_workspace: true
          jobs:
            deploy:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks tf_plan create
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks tf_apply
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks wait_ecs
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks smoke_test
